## Creating EC2 instance using ansible playbook###

  tasks:
    - name: startup new instance
      ec2:
         key_name: "{{ keypair }}"
         groups: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         assign_public_ip: yes
         vpc_subnet_id: "subnet-XXXXXXXXXXXXXXXX"
         aws_access_key: "{{ user_access_key }}"
         aws_secret_key: "{{ user_secret_key }}" 


### Installing Jenkins on EC2 machine ansible playbook###

- name: update all packages
  yum:
    name: '*'
    state: latest

- name: install openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add the Jenkins repo
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import a key file from Jenkins-CI
  rpm_key:
     state: present
     key: "{{ gpg_key }}"

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
     name: jenkins
     state: started
     enabled: true
- name: sleep for 30 seconds
  wait_for:
     timeout: 30


### Executing anisbile command to run jenkins and Printing Jenkins Password ####

ansible-playbook -i createec2-installjenkinsonec2-ansible-playbook.yaml

echo "/var/jenkins_home/secrets/IntialAdminPassword"
